import { useEffect, useState } from "react";
import Modal from "../common/Modal";
import "../../styles/AddStudentModal.css";

function AddStudentModal({ show, onClose, student, isEditMode }) {
    const [firstName, setFirstName] = useState("");
    const [lastName, setLastName] = useState("");
    const [gender, setGender] = useState("Male");
    const [dob, setDob] = useState("");
    const [email, setEmail] = useState("");
    const [contact, setContact] = useState("");
    const [course, setCourse] = useState("Select Course");
    const [year, setYear] = useState("1st Year");
    const [status, setStatus] = useState("Active");

    useEffect(() => {
        if (isEditMode && student) {
            const nameParts = student.name.split(" ");
            setFirstName(nameParts[0] || "");
            setLastName(nameParts.slice(1).join(" ") || "");
            setCourse(student.course || "Select Course");
            setYear(student.year || "1st Year");
            setStatus(student.status || "Active");
        } else {
            setFirstName("");
            setLastName("");
            setGender("Male");
            setDob("");
            setEmail("");
            setContact("");
            setCourse("Select Course");
            setYear("1st Year");
            setStatus("Active");
        }
    }, [student, isEditMode, show]);

    if (!show) return null;

    return (
        <Modal
            show={show}
            title={isEditMode ? "Edit Student Details" : "Add New Student"}
            onClose={onClose}
            width="720px"
            footer={
                <>
                    <button className="cancel-btn" onClick={onClose}>
                        Cancel
                    </button>
                    <button className="save-btn">
                        {isEditMode ? "Update Changes" : "Save Student"}
                    </button>
                </>
            }
        >
            <h5 className="section-title">Personal Information</h5>

            <div className="row">
                <div className="col-md-12 mb-3">
                    <label className="form-label">Student ID</label>
                    <input
                        type="text"
                        className="form-control field-disabled"
                        placeholder={isEditMode && student ? student.id : "Auto-generated by system..."}
                        disabled
                    />
                </div>

                <div className="col-md-6 mb-3">
                    <label className="form-label">First Name</label>
                    <input 
                        type="text" 
                        className="form-control" 
                        value={firstName} 
                        onChange={(e) => setFirstName(e.target.value)}
                        placeholder="Enter first name" 
                    />
                </div>

                <div className="col-md-6 mb-3">
                    <label className="form-label">Last Name</label>
                    <input 
                        type="text" 
                        className="form-control" 
                        value={lastName}
                        onChange={(e) => setLastName(e.target.value)}
                        placeholder="Enter last name" 
                    />
                </div>

                <div className="col-md-6 mb-3">
                    <label className="form-label">Gender</label>
                    <select className="form-select" value={gender} onChange={(e) => setGender(e.target.value)}>
                        <option>Male</option>
                        <option>Female</option>
                    </select>
                </div>

                <div className="col-md-6 mb-3">
                    <label className="form-label">Date of Birth</label>
                    <input type="date" className="form-control" value={dob} onChange={(e) => setDob(e.target.value)} />
                </div>
            </div>

            <h5 className="section-title">Contact Information</h5>

            <div className="row">
                <div className="col-md-6 mb-3">
                    <label className="form-label">Email Address</label>
                    <input 
                        type="email" 
                        className="form-control" 
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        placeholder="example@email.com" 
                    />
                </div>

                <div className="col-md-6 mb-3">
                    <label className="form-label">Contact Number</label>
                    <input 
                        type="text" 
                        className="form-control" 
                        value={contact}
                        onChange={(e) => setContact(e.target.value)}
                        placeholder="09XXXXXXXXX" 
                    />
                </div>
            </div>

            <h5 className="section-title">Academic Information</h5>

            <div className="row">
                <div className="col-md-4 mb-3">
                    <label className="form-label">Course</label>
                    <select className="form-select" value={course} onChange={(e) => setCourse(e.target.value)}>
                        <option>Select Course</option>
                        <option>BSIT</option>
                        <option>BSBA</option>
                        <option>BSHM</option>
                        <option>BSTM</option>
                    </select>
                </div>

                <div className="col-md-4 mb-3">
                    <label className="form-label">Year Level</label>
                    <select className="form-select" value={year} onChange={(e) => setYear(e.target.value)}>
                        <option>1st Year</option>
                        <option>2nd Year</option>
                        <option>3rd Year</option>
                        <option>4th Year</option>
                    </select>
                </div>

                <div className="col-md-4 mb-3">
                    <label className="form-label">Status</label>
                    <select className="form-select" value={status} onChange={(e) => setStatus(e.target.value)}>
                        <option>Active</option>
                        <option>Inactive</option>
                    </select>
                </div>
            </div>
        </Modal>
    );
}

export default AddStudentModal;